# Generated by Django 5.0.7 on 2024-07-20 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
